@startuml gestionedispositivi

title "Gestione Dispositivi"
left to right direction

actor Utente

usecase "Aggiungi Dispositivo" as Aggiungi
usecase "Rimuovi Dispositivo" as Rimuovi
usecase "configura Dispositivo" as Configura
usecase "Visualizza Lista dispositivi" as Visualizza

Utente -- Aggiungi
Utente -- Rimuovi
Utente -- Configura
Utente -- Visualizza

@enduml