@startuml gestioneaccount

title "Gestione Account"
left to right direction

actor Utente

usecase "Effettua Login" as Login
usecase "Lista Utenti" as Lista
usecase "Registra Utente" as Registra
usecase "Nuovo Account" as Nuovo
usecase "Rimuovi Account" as Cancella

Utente -- Login
Utente -- Lista
Utente -- Registra
Utente -- Nuovo
Utente -- Cancella

Registra ..> Login: <<include>>

@enduml