@startuml gestionesistema

title "Gestione Sistema"
left to right direction

actor Tempo
actor Utente

usecase "Visualizza Stato" as Visualizza
usecase "Esegui Backup" as Esegui

Tempo -- Esegui
Utente -- Visualizza

@enduml