@startuml
actor Utente
participant Sistema

Utente -> Sistema : seleziona l'ID della zona esistente
activate Sistema

Utente -> Sistema : seleziona l'ID dell'attuatore da inserire

alt attuatore già associato alla zona
    Sistema --> Utente : attuatore dissociato con successo
else attuatore non associato alla zona
    Sistema --> Utente : attuatore associato con successo
end

deactivate Sistema
@enduml