@startuml
actor Utente
participant Form <<boundary>>
participant GestoreZone <<control>>

Utente -> Form : seleziona l'ID della zona
activate Form

Utente -> Form : seleziona l'ID dell'attuatore

alt attuatore NON associato alla zona
    Form -> GestoreZone : associaAttuatoreZona()
    activate GestoreZone
    GestoreZone --> Form : associazione effettuata
    deactivate GestoreZone
else attuatore GIA' associato alla zona
    Form -> GestoreZone : rimuoviAttuatoreDaZona()
    activate GestoreZone
    GestoreZone --> Form : dissociazione effettuata
    deactivate GestoreZone
end

Form --> Utente : attuatore associato/dissociato con successo
deactivate Form
@enduml