@startuml
actor Utente
participant Form <<boundary>>
participant GestoreZone <<control>>

Utente -> Form : seleziona "Orario"
activate Form

Utente -> Form : inserisce l'ID della zona
Utente -> Form : inserisce l'orario di attivazione
Utente -> Form : inserisce l'orario di disattivazione

Form -> GestoreZone : impostaProgramazioneOraria()
activate GestoreZone

GestoreZone --> Form : programmazione oraria impostata
deactivate GestoreZone

Form --> Utente : Pianificazione zona completata
deactivate Form
@enduml