@startuml
actor Utente
participant Form <<boundary>>
participant GestoreZone <<control>>
participant Zona <<entity>>

Utente -> Form : seleziona "Rimuovi Zona"
activate Form

Utente -> Form : inserisce l'ID della zona da rimuovere

Form -> GestoreZone : eliminaZona(Zona)
activate GestoreZone

GestoreZone -> Zona !! : <<distruggi>>
destroy Zona

GestoreZone --> Form : rimozione effettuata
deactivate GestoreZone

Form --> Utente : zona eliminata con successo
deactivate Form
@enduml