@startuml
actor Utente
participant Sistema
participant Zona

Utente -> Sistema : seleziona "Rimuovi Zona"
activate Sistema

Utente -> Sistema : inserisce l'ID della zona da rimuovere
Sistema -> Zona !! : <<distruggi>>
destroy Zona

Sistema --> Utente : zona eliminata con successo
deactivate Sistema
@enduml