@startuml cancaellaaccount
title Elimina account

start

:Seleziona account da eliminare;

if (Account esiste) then (si)
    :Seleziona "Elimina account";
    :Account eliminato;
else (no)
    :Mostra messaggio di errore;
endif

stop
@enduml