@startuml configuraDispositivo
title configura Dispositivo

start

:Inserisci ID dispositivo;

if (Dispositivo esiste) then (si)
    :Imposta configurazione;
    :La configurazione viene applicata;
else (no)
    :Mostra messaggio di errore;
stop
@enduml