@startuml configuraZona
title configura zona

start

:Seleziona aggiungi zona;
:Inserisci dati;

if (Zona esiste) then (si)
    :Imposta configurazione;
    :La configurazione viene applicata;
else (no)
    :Mostra messaggio di errore;
stop
@enduml