@startuml creaAccount
title Crea account

start

:Seleziona registrazione;
:Inserisci dati;

if (Account esiste) then (si)
    :Mostra messaggio di errore;
else (no)
    :Crea account;
endif

stop
@enduml