@startuml creaScenario
title Crea scenario

start

:Seleziona aggiungi Scenario;
:Inserisci dati;

if (Scenario esiste) then (si)
    :Mostra messaggio di errore;
else (no)
    :Crea Scenario;
endif

stop
@enduml