@startuml eliminazona
title Elimina zona


if (Zona esiste) then (si)
    :Seleziona "Elimina zona";
    :Seleziona zona;
    :Elimina zona selezionata;
    :Zona eliminata;
else (no)
    :Mostra messaggio di errore;
endif

stop
@enduml