@startuml eliminascenario
title Elimina scenario

start

    if (Scenario esiste) then (si)
        :Seleziona "Elimina scenario";
        :Seleziona scenario da eliminare;
        :Lo scenario viene eliminato;
    else (no)
        :Mostra messaggio di errore;
    endif
stop
@enduml