@startuml rimuoviDispositivo
title rimuovi Dispositivo

start

:Seleziona rimuovi dispositivo;

if (Dispositivo esiste) then (si)
    :Elimina dispositivo;
else (no)
    :Mostra messaggio di errore;
endif

stop
@enduml