@startuml recuperaContenutoBackup
title Ripristina il sistema dall'ultimo backup

start
if (Esiste un backup?) then (si)
    :Recupera i file di backup;
    :Ripristina il backup recuperato;
    :Il backup è stato ripristinato;
else (no)
endif
stop

@enduml
