@startuml
actor Utente
participant Form <<boundary>>
participant GestoreScenari <<control>>
participant Scenario <<entity>>

Utente -> Form : seleziona "Aggiungi Scenario"
activate Form

Utente -> Form : inserisce l'ID dello scenario
Utente -> Form : inserisce il nome dello scenario

Form -> GestoreScenari : creaScenario()
activate GestoreScenari

GestoreScenari -> Scenario ** : <<crea>>
activate Scenario
Scenario --> GestoreScenari
deactivate Scenario

GestoreScenari --> Form : scenario generato
deactivate GestoreScenari

Form --> Utente : Scenario creato con successo
deactivate Form
@enduml