@startuml
actor Utente
participant Form <<boundary>>
participant GestoreScenari <<control>>

Utente -> Form : seleziona l'ID dello scenario
activate Form

Utente -> Form : seleziona l'ID dell'attuatore

alt attuatore NON associato allo scenario
    Form -> GestoreScenari : associaAttuatoreScenario()
    activate GestoreScenari
    GestoreScenari --> Form : associazione effettuata
    deactivate GestoreScenari
else attuatore GIA' associato allo scenario
    Form -> GestoreScenari : rimuoviAttuatoreDaScenario()
    activate GestoreScenari
    GestoreScenari --> Form : dissociazione effettuata
    deactivate GestoreScenari
end

Form --> Utente : Attuatore associato/disassociato con successo
deactivate Form
@enduml