@startuml
actor Utente
participant Form <<boundary>>
participant GestoreScenari <<control>>

Utente -> Form : inserisce l'ID dello scenario desiderato
activate Form

Utente -> Form : inserisce l'ID del sensore da associare
Utente -> Form : inserisce la soglia desiderata del sensore

Form -> GestoreScenari : impostaAutomazioneSensore()
activate GestoreScenari

GestoreScenari --> Form : associazione effettuata
deactivate GestoreScenari

Form --> Utente : Sensore associato con successo
deactivate Form
@enduml