@startuml
actor Utente
participant Form <<boundary>>
participant GestoreScenari <<control>>

Utente -> Form : seleziona "Lista Scenari"
activate Form

Form -> GestoreScenari : listaScenari()
activate GestoreScenari

GestoreScenari --> Form : restituisce la lista degli scenari
deactivate GestoreScenari

Form --> Utente : visualizza la lista degli scenari esistenti
deactivate Form
@enduml