@startuml
actor Utente
participant Form <<boundary>>
participant GestoreScenari <<control>>

Utente -> Form : seleziona l'ID dello scenario
activate Form

Utente -> Form : inserisce l'orario di attivazione
Utente -> Form : inserisce l'orario di disattivazione

Form -> GestoreScenari : impostaProgramazioneOraria()
activate GestoreScenari

GestoreScenari --> Form : programmazione oraria impostata
deactivate GestoreScenari

Form --> Utente : automazione dello scenario configurata
deactivate Form
@enduml