@startuml
actor Utente
participant Sistema

Utente -> Sistema : seleziona l'ID dello scenario da automatizzare
activate Sistema

Utente -> Sistema : inserisce l'orario di attivazione
Utente -> Sistema : inserisce l'orario di disattivazione

Sistema --> Utente : automazione dello scenario configurata
deactivate Sistema
@enduml