@startuml
actor Utente
participant Form <<boundary>>
participant GestoreScenari <<control>>
participant Scenario <<entity>>

Utente -> Form : seleziona "Rimuovi scenario"
activate Form

Utente -> Form : inserisce l'ID dello scenario da eliminare

Form -> GestoreScenari : eliminaScenario(Scenario)
activate GestoreScenari

GestoreScenari -> Scenario !! : <<distruggi>>
destroy Scenario

GestoreScenari --> Form : rimozione effettuata
deactivate GestoreScenari

Form --> Utente : scenario eliminato con successo
deactivate Form
@enduml