@startuml

title sd CreaScenario

actor Admin

participant "<<boundary>>\n:Centralina"
participant "<<control>>\n:GestoreScenari"
participant "<<repository>>\n:ScenarioRepository"
participant "<<entity>>\n:Scenario"
participant "<<entity>>\n:Attuatore"

Admin -> "<<boundary>>\n:Centralina" : selezionaCreaScenario()
activate "<<boundary>>\n:Centralina"

loop forEach attuatore da configurare
    Admin -> "<<boundary>>\n:Centralina" : configuraStatoAttuatore()
    "<<boundary>>\n:Centralina" -> "<<control>>\n:GestoreScenari" : aggiungiConfigurazione()
    activate "<<control>>\n:GestoreScenari"
    
    "<<control>>\n:GestoreScenari" -> "<<entity>>\n:Attuatore" : getDati()
    activate "<<entity>>\n:Attuatore"
    "<<entity>>\n:Attuatore" --> "<<control>>\n:GestoreScenari" : attuatore
    deactivate "<<entity>>\n:Attuatore"
    
    "<<control>>\n:GestoreScenari" --> "<<boundary>>\n:Centralina" : attuatore
    deactivate "<<control>>\n:GestoreScenari"
end

"<<boundary>>\n:Centralina" -> "<<control>>\n:GestoreScenari" : salvaScenario()
activate "<<control>>\n:GestoreScenari"

"<<control>>\n:GestoreScenari" -> "<<entity>>\n:Scenario" : inizializza()
activate "<<entity>>\n:Scenario"
"<<entity>>\n:Scenario" --> "<<control>>\n:GestoreScenari" : nuovoScenario
deactivate "<<entity>>\n:Scenario"

"<<control>>\n:GestoreScenari" -> "<<repository>>\n:ScenarioRepository" : salvaScenario()
activate "<<repository>>\n:ScenarioRepository"
"<<repository>>\n:ScenarioRepository" --> "<<control>>\n:GestoreScenari" : nuovoScenario
deactivate "<<repository>>\n:ScenarioRepository"

alt operazione riuscita
    "<<control>>\n:GestoreScenari" --> "<<boundary>>\n:Centralina" : nuovoScenario
    "<<boundary>>\n:Centralina" --> Admin : confermaCreazione()
else else
    "<<control>>\n:GestoreScenari" --> "<<boundary>>\n:Centralina" : errore
    "<<boundary>>\n:Centralina" --> Admin : mostraErrore()
end

deactivate "<<control>>\n:GestoreScenari"
deactivate "<<boundary>>\n:Centralina"

@enduml