@startuml

title sd EffettuaLogin

actor Utente

participant "<<boundary>>\n:Centralina"
participant "<<control>>\n:GestoreUtenti"
participant "<<repository>>\n:UserRepository"
participant "<<entity>>\n:Utente"

Utente -> "<<boundary>>\n:Centralina" : inserisciCredenziali()
activate "<<boundary>>\n:Centralina"

"<<boundary>>\n:Centralina" -> "<<control>>\n:GestoreUtenti" : autentica()
activate "<<control>>\n:GestoreUtenti"

"<<control>>\n:GestoreUtenti" -> "<<repository>>\n:UserRepository" : getUtente()
activate "<<repository>>\n:UserRepository"
"<<repository>>\n:UserRepository" --> "<<control>>\n:GestoreUtenti" : utente
deactivate "<<repository>>\n:UserRepository"

alt l'utente esiste
    "<<control>>\n:GestoreUtenti" -> "<<entity>>\n:Utente" : verificaPassword()
    activate "<<entity>>\n:Utente"
    "<<entity>>\n:Utente" --> "<<control>>\n:GestoreUtenti" : esito
    deactivate "<<entity>>\n:Utente"
    
    alt credenziali corrette
        "<<control>>\n:GestoreUtenti" --> "<<boundary>>\n:Centralina" : loginSuccesso()
        "<<boundary>>\n:Centralina" --> Utente : visualizzaDashboard()
    else else
        "<<control>>\n:GestoreUtenti" --> "<<boundary>>\n:Centralina" : errore()
        "<<boundary>>\n:Centralina" --> Utente : mostraErrore()
    end
    
else else
    "<<control>>\n:GestoreUtenti" --> "<<boundary>>\n:Centralina" : errore()
    "<<boundary>>\n:Centralina" --> Utente : mostraErrore()
end

deactivate "<<control>>\n:GestoreUtenti"
deactivate "<<boundary>>\n:Centralina"

@enduml