@startuml

title sd AggiungiDispositivo

actor Admin

participant "<<boundary>>\n:Centralina"
participant "<<control>>\n:GestoreDispositivi"
participant "<<repository>>\n:DispositivoRepository"
participant "<<entity>>\n:Dispositivo"

Admin -> "<<boundary>>\n:Centralina" : selezionaAggiungiDispositivo()
activate "<<boundary>>\n:Centralina"

Admin -> "<<boundary>>\n:Centralina" : inserisciDatiDispositivo()

"<<boundary>>\n:Centralina" -> "<<control>>\n:GestoreDispositivi" : aggiungiDispositivo()
activate "<<control>>\n:GestoreDispositivi"

"<<control>>\n:GestoreDispositivi" -> "<<entity>>\n:Dispositivo" : inizializza()
activate "<<entity>>\n:Dispositivo"
"<<entity>>\n:Dispositivo" --> "<<control>>\n:GestoreDispositivi" : nuovoDispositivo
deactivate "<<entity>>\n:Dispositivo"

"<<control>>\n:GestoreDispositivi" -> "<<repository>>\n:DispositivoRepository" : salvaDispositivo()
activate "<<repository>>\n:DispositivoRepository"
"<<repository>>\n:DispositivoRepository" --> "<<control>>\n:GestoreDispositivi" : nuovoDispositivo
deactivate "<<repository>>\n:DispositivoRepository"

alt operazione riuscita
    "<<control>>\n:GestoreDispositivi" --> "<<boundary>>\n:Centralina" : nuovoDispositivo
    "<<boundary>>\n:Centralina" --> Admin : confermaAggiunta()
else else
    "<<control>>\n:GestoreDispositivi" --> "<<boundary>>\n:Centralina" : errore
    "<<boundary>>\n:Centralina" --> Admin : mostraErrore()
end

deactivate "<<control>>\n:GestoreDispositivi"
deactivate "<<boundary>>\n:Centralina"

@enduml