@startuml modificascenario
title Modifica scenario

start

    if (Scenario esiste) then (si)
        :Seleziona "Modifica scenario";
        :Configura le modifiche allo scenario;
        :Lo scenario viene modificato;
    else (no)
        :Mostra messaggio di errore;
    endif

stop
@enduml