@startuml

title sd CreaAccount

actor Admin

participant "<<boundary>>\n:Centralina"
participant "<<control>>\n:GestoreUtenti"
participant "<<repository>>\n:UserRepository"
participant "<<entity>>\n:Utente"

Admin -> "<<boundary>>\n:Centralina" : selezionaCreaAccount()
activate "<<boundary>>\n:Centralina"

Admin -> "<<boundary>>\n:Centralina" : inserisciDatiAccount()

"<<boundary>>\n:Centralina" -> "<<control>>\n:GestoreUtenti" : creaAccount()
activate "<<control>>\n:GestoreUtenti"

"<<control>>\n:GestoreUtenti" -> "<<entity>>\n:Utente" : inizializza()
activate "<<entity>>\n:Utente"
"<<entity>>\n:Utente" --> "<<control>>\n:GestoreUtenti" : nuovoAccount
deactivate "<<entity>>\n:Utente"

"<<control>>\n:GestoreUtenti" -> "<<repository>>\n:UserRepository" : salvaAccount()
activate "<<repository>>\n:UserRepository"
"<<repository>>\n:UserRepository" --> "<<control>>\n:GestoreUtenti" : nuovoAccount
deactivate "<<repository>>\n:UserRepository"

alt operazione riuscita
    "<<control>>\n:GestoreUtenti" --> "<<boundary>>\n:Centralina" : nuovoAccount
    "<<boundary>>\n:Centralina" --> Admin : confermaCreazione()
else else
    "<<control>>\n:GestoreUtenti" --> "<<boundary>>\n:Centralina" : errore
    "<<boundary>>\n:Centralina" --> Admin : mostraErrore()
end

deactivate "<<control>>\n:GestoreUtenti"
deactivate "<<boundary>>\n:Centralina"

@enduml