@startuml

title sd CreaZona

actor Admin

participant "<<boundary>>\n:Centralina"
participant "<<control>>\n:GestoreZone"
participant "<<repository>>\n:ZonaRepository"
participant "<<entity>>\n:Zona"
participant "<<entity>>\n:Dispositivo"

Admin -> "<<boundary>>\n:Centralina" : selezionaCreaZona()
activate "<<boundary>>\n:Centralina"

loop forEach dispositivo da includere
    Admin -> "<<boundary>>\n:Centralina" : selezionaDispositivo()
    "<<boundary>>\n:Centralina" -> "<<control>>\n:GestoreZone" : aggiungiDispositivo()
    activate "<<control>>\n:GestoreZone"
    
    "<<control>>\n:GestoreZone" -> "<<entity>>\n:Dispositivo" : getDispositivo()
    activate "<<entity>>\n:Dispositivo"
    "<<entity>>\n:Dispositivo" --> "<<control>>\n:GestoreZone" : dispositivo
    deactivate "<<entity>>\n:Dispositivo"
    
    "<<control>>\n:GestoreZone" --> "<<boundary>>\n:Centralina" : dispositivo
    deactivate "<<control>>\n:GestoreZone"
end

"<<boundary>>\n:Centralina" -> "<<control>>\n:GestoreZone" : confermaCreazione()
activate "<<control>>\n:GestoreZone"

"<<control>>\n:GestoreZone" -> "<<entity>>\n:Zona" : inizializza()
activate "<<entity>>\n:Zona"
"<<entity>>\n:Zona" --> "<<control>>\n:GestoreZone" : nuovaZona
deactivate "<<entity>>\n:Zona"

"<<control>>\n:GestoreZone" -> "<<repository>>\n:ZonaRepository" : salvaZona()
activate "<<repository>>\n:ZonaRepository"
"<<repository>>\n:ZonaRepository" --> "<<control>>\n:GestoreZone" : nuovaZona
deactivate "<<repository>>\n:ZonaRepository"

alt operazione riuscita
    "<<control>>\n:GestoreZone" --> "<<boundary>>\n:Centralina" : nuovaZona
    "<<boundary>>\n:Centralina" --> Admin : confermaCreazione()
else else
    "<<control>>\n:GestoreZone" --> "<<boundary>>\n:Centralina" : errore
    "<<boundary>>\n:Centralina" --> Admin : mostraErrore()
end

deactivate "<<control>>\n:GestoreZone"
deactivate "<<boundary>>\n:Centralina"

@enduml