@startuml
actor Utente
participant Form <<boundary>>
participant GestoreDispositivi <<control>>

Utente -> Form : inserisce l'ID del dispositivo da configurare
activate Form

Utente -> Form : inserisce l'eventuale soglia
Utente -> Form : inserisce l'eventuale stato
Utente -> Form : inserisce il nuovo orario di attivazione

Form -> GestoreDispositivi : configuraDispositivo(Dispositivo)
activate GestoreDispositivi

GestoreDispositivi --> Form : configurazione effettuata
deactivate GestoreDispositivi

Form --> Utente : dispositivo configurato con successo
deactivate Form
@enduml