@startuml
actor Utente
participant Form <<boundary>>
participant GestoreDispositivi <<control>>
participant Dispositivo <<entity>>

Utente -> Form : inserisce l'ID del dispositivo da eliminare
activate Form

Form -> GestoreDispositivi : rimuoviDispositivo(Dispositivo)
activate GestoreDispositivi

GestoreDispositivi -> Dispositivo !! : <<distruggi>>
destroy Dispositivo

GestoreDispositivi --> Form : rimozione effettuata
deactivate GestoreDispositivi

Form --> Utente : dispositivo rimosso con successo
deactivate Form
@enduml