@startuml
actor Utente
participant Form <<boundary>>
participant GestoreDispositivi <<control>>

Utente -> Form : seleziona "Lista Dispositivi"
activate Form

Form -> GestoreDispositivi : lista()
activate GestoreDispositivi

GestoreDispositivi --> Form : restituisce la lista dei dispositivi
deactivate GestoreDispositivi

Form --> Utente : visualizza i dispositivi esistenti
deactivate Form
@enduml