@startuml
actor Utente
participant Form <<boundary>>
participant GestoreDispositivi <<control>>
participant GestoreDati <<control>>

Utente -> Form : seleziona "stato"
activate Form

Form -> GestoreDispositivi : lista()
activate GestoreDispositivi
GestoreDispositivi --> Form : restituisce ID, stato e orario dei dispositivi
deactivate GestoreDispositivi

Form -> GestoreDati : recuperaContenutoBackup(GestoreDati)
activate GestoreDati
GestoreDati --> Form : restituisce dati dell'ultimo backup
deactivate GestoreDati

Form --> Utente : visualizza dispositivi e ultimo backup
deactivate Form
@enduml