@startuml analisireq
title "Analisi dei requisiti"
left to right direction
<style>
frame {
    LineThickness 2
}
file {
    LineThickness 1.5
}
card{
    LineThickness 1
}
</style>

frame "Analisi dei requisiti" {
    file "Requisiti funzionali: descrivono le caratteristiche, le funzionalità generali ed \nil comportamento che il sistema proposto deve supportare" #FFFFFF {
        file "Must have" #F5F1B3 {
                card "RF1-Accesso utente" #DDF5D7
                card "RF2-Backup dati" #DDF5D7
                card "RF3-Gestione\nsoglie sensori" #DDF5D7
                card "RF4-Attivazione\nauto attuatori" #DDF5D7
                card "RF5-Disattivazione\nauto attuatori" #DDF5D7
                card "RF6-Visualizza\nstato sensori" #DDF5D7
                card "RF7-Visualizza\nstato attuatori" #DDF5D7
                card "RF8-Pianificazione\nfasce orarie" #DDF5D7
                card "RF9-Aggiunta\nnuovi dispositivi" #DDF5D7
                card "RF10-Rimozione\ndispositivi" #DDF5D7
                card "RF11-Controllo\nmanuale attuatori" #DDF5D7        
        }
        file "Should have" #F5F1B3 {
                card "RF12-Configurazione\nnuovi account" #DDF5D7
                card "RF13-Eliminazione\naccount" #DDF5D7
                card "RF14-Configurazione\nzone" #DDF5D7
                card "RF15-Modifica stato\nattuatori zona" #DDF5D7
                card "RF16-Visualizzazione\nsensore zona" #DDF5D7
                card "RF17-Visualizzazione\nsensore scenario"#DDF5D7
                card "RF18-Configurazione\nscenario" #DDF5D7
                card "RF19-Modifica\nscenario" #DDF5D7
                card "RF20-Eliminazione\nscenario" #DDF5D7
                card "RF21-Creazione\nscenario" #DDF5D7
                card "RF22-Creazione\nzone" #DDF5D7
        }
        file "Could have" #F5F1B3 {
                card "RF23-Notifica\nerrori sistema" #DDF5D7
        }
        file "Want to have" #F5F1B3 {
                card "RF24-Monitoraggio\ndispositivi" #DDF5D7
                card "RNF25-Ottimizzazione\nprestazioni" #DDF5D7
                card "RNF26-Risparmio\nenergetico e report" #DDF5D7
        }
    }
    file "Requisiti non funzionali: sono tutti gli altri vincoli \nche influenzano il sistema ed il suo sviluppo " #FFFFFF {
        file "Requisiti non funzionali " #F5F1B3 {
            card "RNF1-Temporizzazione" #DDF5D7
            card "RNF2-Backup\ndati locali" #DDF5D7
            card "RNF3-Implementazione in python 3" #DDF5D7

        }    
    }
}
@enduml