@startuml
actor Utente
participant Form <<boundary>>
participant GestoreUtenti <<control>>

Utente -> Form : inserisce l'ID esistente
activate Form

Utente -> Form : inserisce il nome
Utente -> Form : inserisce la password

Form -> GestoreUtenti : login()
activate GestoreUtenti

GestoreUtenti --> Form : esito positivo
deactivate GestoreUtenti

Form --> Utente : autenticazione completata
deactivate Form
@enduml