@startuml
actor Tempo
participant Form <<boundary>>
participant GestoreDispositivi <<control>>
participant GestoreDati <<control>>
participant Log <<entity>>

Tempo -> Form : trigger timer
activate Form

Form -> GestoreDispositivi : lista()
activate GestoreDispositivi
GestoreDispositivi --> Form : restituisce i dati
deactivate GestoreDispositivi

Form -> GestoreDati : eseguiBackup(dati)
activate GestoreDati

GestoreDati -> Log ** : <<crea>>
activate Log
Log --> GestoreDati
deactivate Log

GestoreDati --> Form : salvataggio completato
deactivate GestoreDati

Form --> Tempo : backup eseguito con successo
deactivate Form
@enduml