@startuml
actor Utente
participant Form <<boundary>>
participant GestoreUtenti <<control>>
participant Account <<entity>>

Utente -> Form : inserisce l'ID non esistente
activate Form

Utente -> Form : inserisce il nome
Utente -> Form : inserisce la password

Form -> GestoreUtenti : creaAccount()
activate GestoreUtenti

GestoreUtenti -> Account ** : <<crea>>
activate Account
Account --> GestoreUtenti
deactivate Account

GestoreUtenti --> Form : nuovo account generato
deactivate GestoreUtenti

Form --> Utente : registrazione completata con successo
deactivate Form
@enduml