@startuml
actor Utente
participant Form <<boundary>>
participant GestoreUtenti <<control>>
participant Account <<entity>>

Utente -> Form : seleziona "Nuovo Account"
activate Form

Utente -> Form : inserisce l'ID del nuovo account
Utente -> Form : inserisce nome e password del nuovo account

Form -> GestoreUtenti : creaAccount()
activate GestoreUtenti

GestoreUtenti -> Account ** : <<crea>>
activate Account
Account --> GestoreUtenti
deactivate Account

GestoreUtenti --> Form : nuovo account generato
deactivate GestoreUtenti

Form --> Utente : nuovo account creato con successo
deactivate Form
@enduml